pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
            	bat 'javac -cp "C:/Users/alsrud/eclipse/jee-2024-03/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar;SW/src" -encoding UTF-8 -d classes SW/src/BookManagerTest3.java'
            }
        }
        
        stage('Test') {
            steps {
                script {
                    def junitPath = "C:/Users/alsrud/eclipse/jee-2024-03/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
                    def classpath = "classes;lib;${junitPath}"
                    bat "java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath > final_result.txt"
                }
            }
        }
    }
    
    post {
        always {
            archiveArtifacts 'final_result.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}
